import ReactMarkdown from "react-markdown";
import { Analysis } from "@shared/schema";
import { format } from "date-fns";
import { Download, Share2, AlertCircle, BarChart, PieChart, TrendingUp, Activity } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { 
  BarChart as ReBarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  LineChart,
  Line,
  Cell,
  PieChart as RePieChart,
  Pie
} from 'recharts';

export function AnalysisReport({ analysis }: { analysis: Analysis }) {
  const { toast } = useToast();

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    toast({
      title: "Link Copied",
      description: "Analysis link copied to clipboard.",
    });
  };

  return (
    <div className="w-full max-w-6xl mx-auto animate-in fade-in slide-in-from-bottom-8 duration-700 space-y-6">
      {/* Report Header */}
      <div className="bg-card border border-border rounded-2xl p-8 md:p-10 relative overflow-hidden shadow-sm">
        <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
        
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 relative z-10">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider border border-primary/20">
                Visual Market Analysis
              </span>
              <span className="text-muted-foreground text-sm font-mono">
                {format(new Date(analysis.createdAt || Date.now()), "MMM d, yyyy")}
              </span>
            </div>
            <h1 className="text-4xl md:text-6xl font-black tracking-tighter mb-2 text-foreground uppercase italic">
              {analysis.symbol}
            </h1>
            <p className="text-muted-foreground flex items-center gap-2">
              <Activity className="w-4 h-4 text-primary" />
              Dynamic Market Intelligence Report
            </p>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleShare} className="hover-elevate">
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
            <Button variant="outline" size="sm" disabled>
              <Download className="w-4 h-4 mr-2" />
              PDF
            </Button>
          </div>
        </div>
      </div>

      {/* Markdown Content */}
      <div className="bg-white border border-border rounded-2xl p-8 md:p-12 shadow-sm relative">
        <div className="prose prose-lg max-w-none prose-headings:text-primary prose-strong:text-emerald-600">
          <ReactMarkdown>{analysis.report}</ReactMarkdown>
        </div>
        
        <div className="mt-12 pt-8 border-t border-border/50 flex items-start gap-4 text-sm text-muted-foreground bg-secondary/30 p-6 rounded-xl">
          <AlertCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
          <p className="leading-relaxed">
            <strong>Disclaimer:</strong> This graphical report is generated by AI for informational purposes only. 
            It is not financial advice. Technical indicators and fundamental patterns are based on available historical data. 
            Always conduct your own research or consult a certified financial advisor before trading.
          </p>
        </div>
      </div>
    </div>
  );
}
