import ReactMarkdown from "react-markdown";
import { Analysis } from "@shared/schema";
import { format } from "date-fns";
import { Download, Share2, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

export function AnalysisReport({ analysis }: { analysis: Analysis }) {
  const { toast } = useToast();

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    toast({
      title: "Link Copied",
      description: "Analysis link copied to clipboard.",
    });
  };

  return (
    <div className="w-full max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-8 duration-700">
      {/* Report Header */}
      <div className="bg-card border border-border rounded-t-2xl p-8 md:p-10 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
        
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 relative z-10">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <span className="px-3 py-1 rounded-full bg-primary/10 text-primary text-xs font-bold uppercase tracking-wider border border-primary/20">
                Stock Analysis
              </span>
              <span className="text-muted-foreground text-sm font-mono">
                {format(new Date(analysis.createdAt || Date.now()), "MMM d, yyyy • h:mm a")}
              </span>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-2 text-foreground">
              {analysis.symbol}
            </h1>
            <p className="text-muted-foreground">Comprehensive AI-generated market report</p>
          </div>

          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleShare}>
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
            {/* Download could generate a PDF in a real app */}
            <Button variant="outline" size="sm" disabled>
              <Download className="w-4 h-4 mr-2" />
              PDF
            </Button>
          </div>
        </div>
      </div>

      {/* Markdown Content */}
      <div className="bg-background border-x border-b border-border rounded-b-2xl p-8 md:p-12 shadow-2xl shadow-black/20">
        <div className="prose prose-invert prose-lg max-w-none">
          <ReactMarkdown>{analysis.report}</ReactMarkdown>
        </div>
        
        <div className="mt-12 pt-8 border-t border-border/50 flex items-start gap-4 text-sm text-muted-foreground bg-secondary/10 p-6 rounded-xl">
          <AlertCircle className="w-5 h-5 text-primary shrink-0 mt-0.5" />
          <p className="leading-relaxed">
            <strong>Disclaimer:</strong> This report is generated by AI for informational purposes only. 
            It is not financial advice. Market data may be delayed or inaccurate. 
            Always conduct your own research or consult a certified financial advisor before trading.
          </p>
        </div>
      </div>
    </div>
  );
}
